import Head from "next/head";
import { useTheme } from "next-themes";
import { useState, useEffect } from "react";
import Navbar from "@/components/Navbar";
import Page from "@/components/Page";
export default function Home() {
  const [rendered, setRendered] = useState(false);
  useEffect(() => {
    setRendered(true);
  }, []);
  const { theme, setTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Codepencil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar rendered={rendered} />
      <Page>
        {rendered && (
          <button
            onClick={() => {
              setTheme(theme === "light" ? "dark" : "light");
            }}
          >
            {theme}
          </button>
        )}
      </Page>
    </>
  );
}
